drop policy "Allow all for authenticated" on "public"."profiles";

revoke delete on table "public"."profiles" from "anon";

revoke insert on table "public"."profiles" from "anon";

revoke references on table "public"."profiles" from "anon";

revoke select on table "public"."profiles" from "anon";

revoke trigger on table "public"."profiles" from "anon";

revoke truncate on table "public"."profiles" from "anon";

revoke update on table "public"."profiles" from "anon";

revoke delete on table "public"."profiles" from "authenticated";

revoke insert on table "public"."profiles" from "authenticated";

revoke references on table "public"."profiles" from "authenticated";

revoke select on table "public"."profiles" from "authenticated";

revoke trigger on table "public"."profiles" from "authenticated";

revoke truncate on table "public"."profiles" from "authenticated";

revoke update on table "public"."profiles" from "authenticated";

revoke delete on table "public"."profiles" from "service_role";

revoke insert on table "public"."profiles" from "service_role";

revoke references on table "public"."profiles" from "service_role";

revoke select on table "public"."profiles" from "service_role";

revoke trigger on table "public"."profiles" from "service_role";

revoke truncate on table "public"."profiles" from "service_role";

revoke update on table "public"."profiles" from "service_role";

alter table "public"."profiles" drop constraint "profiles_id_fkey";

alter table "public"."profiles" drop constraint "profiles_role_check";

alter table "public"."shipments" drop constraint "shipments_created_by_fkey";

alter table "public"."profiles" drop constraint "profiles_pkey";

drop index if exists "public"."profiles_pkey";

drop table "public"."profiles";


  create table "public"."master_partners" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone default now(),
    "name" text not null,
    "type" text not null,
    "tax_id" text,
    "address" text,
    "contact_person" text,
    "email" text,
    "phone" text,
    "is_active" boolean default true,
    "city" text,
    "phone_cp" text,
    "wa_cp" text,
    "bank_acc" text,
    "no_acc" text,
    "name_acc" text,
    "province" text
      );


alter table "public"."master_partners" enable row level security;


  create table "public"."master_products" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone default now(),
    "sku_code" text not null,
    "name" text not null,
    "type" text not null,
    "description" text,
    "current_price" numeric default 0,
    "unit" text default 'MT'::text
      );


alter table "public"."master_products" enable row level security;


  create table "public"."master_warehouse" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "warehouse_name" text,
    "location" json,
    "phone_number" text,
    "address" text,
    "city" text,
    "province" text,
    "email" text
      );


alter table "public"."master_warehouse" enable row level security;


  create table "public"."user_profiles" (
    "uuid" uuid not null,
    "email" text,
    "user_role" bigint,
    "wh_id" uuid,
    "real_name" text,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
      );


alter table "public"."user_profiles" enable row level security;


  create table "public"."user_roles" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "role_name" text
      );


alter table "public"."user_roles" enable row level security;

CREATE UNIQUE INDEX master_partners_pkey ON public.master_partners USING btree (id);

CREATE UNIQUE INDEX master_products_pkey ON public.master_products USING btree (id);

CREATE UNIQUE INDEX master_products_sku_code_key ON public.master_products USING btree (sku_code);

CREATE UNIQUE INDEX master_warehouse_pkey ON public.master_warehouse USING btree (id);

CREATE UNIQUE INDEX user_profiles_pkey ON public.user_profiles USING btree (uuid);

CREATE UNIQUE INDEX user_roles_pkey ON public.user_roles USING btree (id);

alter table "public"."master_partners" add constraint "master_partners_pkey" PRIMARY KEY using index "master_partners_pkey";

alter table "public"."master_products" add constraint "master_products_pkey" PRIMARY KEY using index "master_products_pkey";

alter table "public"."master_warehouse" add constraint "master_warehouse_pkey" PRIMARY KEY using index "master_warehouse_pkey";

alter table "public"."user_profiles" add constraint "user_profiles_pkey" PRIMARY KEY using index "user_profiles_pkey";

alter table "public"."user_roles" add constraint "user_roles_pkey" PRIMARY KEY using index "user_roles_pkey";

alter table "public"."master_partners" add constraint "master_partners_type_check" CHECK ((type = ANY (ARRAY['SUPPLIER'::text, 'CUSTOMER'::text, 'TRANSPORTER'::text, 'OTHER'::text]))) not valid;

alter table "public"."master_partners" validate constraint "master_partners_type_check";

alter table "public"."master_products" add constraint "master_products_sku_code_key" UNIQUE using index "master_products_sku_code_key";

alter table "public"."master_products" add constraint "master_products_type_check" CHECK ((type = ANY (ARRAY['INTERNAL_RAW'::text, 'PUBLISHED_FINISHED'::text]))) not valid;

alter table "public"."master_products" validate constraint "master_products_type_check";

alter table "public"."user_profiles" add constraint "user_profiles_user_role_fkey" FOREIGN KEY (user_role) REFERENCES public.user_roles(id) ON DELETE SET NULL not valid;

alter table "public"."user_profiles" validate constraint "user_profiles_user_role_fkey";

alter table "public"."user_profiles" add constraint "user_profiles_uuid_fkey" FOREIGN KEY (uuid) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."user_profiles" validate constraint "user_profiles_uuid_fkey";

alter table "public"."user_profiles" add constraint "user_profiles_wh_id_fkey" FOREIGN KEY (wh_id) REFERENCES public.master_warehouse(id) not valid;

alter table "public"."user_profiles" validate constraint "user_profiles_wh_id_fkey";

grant delete on table "public"."master_partners" to "anon";

grant insert on table "public"."master_partners" to "anon";

grant references on table "public"."master_partners" to "anon";

grant select on table "public"."master_partners" to "anon";

grant trigger on table "public"."master_partners" to "anon";

grant truncate on table "public"."master_partners" to "anon";

grant update on table "public"."master_partners" to "anon";

grant delete on table "public"."master_partners" to "authenticated";

grant insert on table "public"."master_partners" to "authenticated";

grant references on table "public"."master_partners" to "authenticated";

grant select on table "public"."master_partners" to "authenticated";

grant trigger on table "public"."master_partners" to "authenticated";

grant truncate on table "public"."master_partners" to "authenticated";

grant update on table "public"."master_partners" to "authenticated";

grant delete on table "public"."master_partners" to "postgres";

grant insert on table "public"."master_partners" to "postgres";

grant references on table "public"."master_partners" to "postgres";

grant select on table "public"."master_partners" to "postgres";

grant trigger on table "public"."master_partners" to "postgres";

grant truncate on table "public"."master_partners" to "postgres";

grant update on table "public"."master_partners" to "postgres";

grant delete on table "public"."master_partners" to "service_role";

grant insert on table "public"."master_partners" to "service_role";

grant references on table "public"."master_partners" to "service_role";

grant select on table "public"."master_partners" to "service_role";

grant trigger on table "public"."master_partners" to "service_role";

grant truncate on table "public"."master_partners" to "service_role";

grant update on table "public"."master_partners" to "service_role";

grant delete on table "public"."master_products" to "anon";

grant insert on table "public"."master_products" to "anon";

grant references on table "public"."master_products" to "anon";

grant select on table "public"."master_products" to "anon";

grant trigger on table "public"."master_products" to "anon";

grant truncate on table "public"."master_products" to "anon";

grant update on table "public"."master_products" to "anon";

grant delete on table "public"."master_products" to "authenticated";

grant insert on table "public"."master_products" to "authenticated";

grant references on table "public"."master_products" to "authenticated";

grant select on table "public"."master_products" to "authenticated";

grant trigger on table "public"."master_products" to "authenticated";

grant truncate on table "public"."master_products" to "authenticated";

grant update on table "public"."master_products" to "authenticated";

grant delete on table "public"."master_products" to "postgres";

grant insert on table "public"."master_products" to "postgres";

grant references on table "public"."master_products" to "postgres";

grant select on table "public"."master_products" to "postgres";

grant trigger on table "public"."master_products" to "postgres";

grant truncate on table "public"."master_products" to "postgres";

grant update on table "public"."master_products" to "postgres";

grant delete on table "public"."master_products" to "service_role";

grant insert on table "public"."master_products" to "service_role";

grant references on table "public"."master_products" to "service_role";

grant select on table "public"."master_products" to "service_role";

grant trigger on table "public"."master_products" to "service_role";

grant truncate on table "public"."master_products" to "service_role";

grant update on table "public"."master_products" to "service_role";

grant delete on table "public"."master_warehouse" to "anon";

grant insert on table "public"."master_warehouse" to "anon";

grant references on table "public"."master_warehouse" to "anon";

grant select on table "public"."master_warehouse" to "anon";

grant trigger on table "public"."master_warehouse" to "anon";

grant truncate on table "public"."master_warehouse" to "anon";

grant update on table "public"."master_warehouse" to "anon";

grant delete on table "public"."master_warehouse" to "authenticated";

grant insert on table "public"."master_warehouse" to "authenticated";

grant references on table "public"."master_warehouse" to "authenticated";

grant select on table "public"."master_warehouse" to "authenticated";

grant trigger on table "public"."master_warehouse" to "authenticated";

grant truncate on table "public"."master_warehouse" to "authenticated";

grant update on table "public"."master_warehouse" to "authenticated";

grant delete on table "public"."master_warehouse" to "postgres";

grant insert on table "public"."master_warehouse" to "postgres";

grant references on table "public"."master_warehouse" to "postgres";

grant select on table "public"."master_warehouse" to "postgres";

grant trigger on table "public"."master_warehouse" to "postgres";

grant truncate on table "public"."master_warehouse" to "postgres";

grant update on table "public"."master_warehouse" to "postgres";

grant delete on table "public"."master_warehouse" to "service_role";

grant insert on table "public"."master_warehouse" to "service_role";

grant references on table "public"."master_warehouse" to "service_role";

grant select on table "public"."master_warehouse" to "service_role";

grant trigger on table "public"."master_warehouse" to "service_role";

grant truncate on table "public"."master_warehouse" to "service_role";

grant update on table "public"."master_warehouse" to "service_role";

grant delete on table "public"."user_profiles" to "anon";

grant insert on table "public"."user_profiles" to "anon";

grant references on table "public"."user_profiles" to "anon";

grant select on table "public"."user_profiles" to "anon";

grant trigger on table "public"."user_profiles" to "anon";

grant truncate on table "public"."user_profiles" to "anon";

grant update on table "public"."user_profiles" to "anon";

grant delete on table "public"."user_profiles" to "authenticated";

grant insert on table "public"."user_profiles" to "authenticated";

grant references on table "public"."user_profiles" to "authenticated";

grant select on table "public"."user_profiles" to "authenticated";

grant trigger on table "public"."user_profiles" to "authenticated";

grant truncate on table "public"."user_profiles" to "authenticated";

grant update on table "public"."user_profiles" to "authenticated";

grant delete on table "public"."user_profiles" to "service_role";

grant insert on table "public"."user_profiles" to "service_role";

grant references on table "public"."user_profiles" to "service_role";

grant select on table "public"."user_profiles" to "service_role";

grant trigger on table "public"."user_profiles" to "service_role";

grant truncate on table "public"."user_profiles" to "service_role";

grant update on table "public"."user_profiles" to "service_role";

grant delete on table "public"."user_roles" to "anon";

grant insert on table "public"."user_roles" to "anon";

grant references on table "public"."user_roles" to "anon";

grant select on table "public"."user_roles" to "anon";

grant trigger on table "public"."user_roles" to "anon";

grant truncate on table "public"."user_roles" to "anon";

grant update on table "public"."user_roles" to "anon";

grant delete on table "public"."user_roles" to "authenticated";

grant insert on table "public"."user_roles" to "authenticated";

grant references on table "public"."user_roles" to "authenticated";

grant select on table "public"."user_roles" to "authenticated";

grant trigger on table "public"."user_roles" to "authenticated";

grant truncate on table "public"."user_roles" to "authenticated";

grant update on table "public"."user_roles" to "authenticated";

grant delete on table "public"."user_roles" to "postgres";

grant insert on table "public"."user_roles" to "postgres";

grant references on table "public"."user_roles" to "postgres";

grant select on table "public"."user_roles" to "postgres";

grant trigger on table "public"."user_roles" to "postgres";

grant truncate on table "public"."user_roles" to "postgres";

grant update on table "public"."user_roles" to "postgres";

grant delete on table "public"."user_roles" to "service_role";

grant insert on table "public"."user_roles" to "service_role";

grant references on table "public"."user_roles" to "service_role";

grant select on table "public"."user_roles" to "service_role";

grant trigger on table "public"."user_roles" to "service_role";

grant truncate on table "public"."user_roles" to "service_role";

grant update on table "public"."user_roles" to "service_role";


  create policy "Enable insert access for authenticated users"
  on "public"."master_partners"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for authenticated users"
  on "public"."master_partners"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Enable update access for authenticated users"
  on "public"."master_partners"
  as permissive
  for update
  to authenticated
using (true);



  create policy "Enable insert access for authenticated users"
  on "public"."master_products"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for authenticated users"
  on "public"."master_products"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Enable update access for authenticated users"
  on "public"."master_products"
  as permissive
  for update
  to authenticated
using (true);



  create policy "Users can insert own profile"
  on "public"."user_profiles"
  as permissive
  for insert
  to public
with check ((( SELECT auth.uid() AS uid) = uuid));



  create policy "Users can update own profile"
  on "public"."user_profiles"
  as permissive
  for update
  to public
using ((( SELECT auth.uid() AS uid) = uuid));



  create policy "Users can view own profile"
  on "public"."user_profiles"
  as permissive
  for select
  to public
using ((( SELECT auth.uid() AS uid) = uuid));



